config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins

  devise_for :users

  root :to => 'pins#index'
  get "about" => "pages#about"
 

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300#", :thumb => "100x100#" }

  validates :image, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :pins

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :set_pin, only: [:show, :edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @pins = Pin.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.build
    respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(params[:pin])
    @pin.save
    respond_with(@pin)
  end

  def update
    @pin.update_attributes(params[:pin])
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

 

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by_id(params[:id])
      redirect_to pins_path, notice: "Not authorized !" if @pin.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Pinteresting</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path%></li>
		    <li><%= link_to "About", about_path%></li>

        <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
          </li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
	<%= render 'layouts/header'%>
	<div class = "container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert, alert-info") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/_home.html.erb
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lobster" />

<div class = "jumbotron center">
	
	<h1  style ="font-family:lobster" > Welcome to my app !</h1>
		<p>
			<%= link_to "Login", new_user_session_path, class: "btn btn-default btn-lg btn-default-bg: #95a5a6"%>
			
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg"%>
		</p>	
</div>

app/views/pages/about.html.erb
<h1>About page</h1>
<p>This is the About page of the Pinteresting application.</p>

app/views/pages/home.html.erb
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lobster" />

<div class = "jumbotron center">
	
	<h1  style ="font-family:lobster" > Welcome to my app !</h1>
	
	<% if user_signed_in? %>
		<b> You're in the members' area ! </b>
	<% else %>
		<p>
			<%= link_to "Login", new_user_session_path, class: "btn btn-default btn-lg btn-default-bg: #95a5a6"%>
			
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg"%>
		</p>
	<% end %>	
	
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: {multipart: true} do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br />
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body text-wrap">
        <p><%= pin.description %></p>
        <p><strong><%= pin.user.name if pin.user %></strong></p>

        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span> Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span> Delete
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class = "panel panel-default">
	<div class = "panel-heading">
		<h1>New pin</h1>
	</div>

	<div class = "panel-body">
		<%= render 'form' %>
	</div>
	<div class = "panel-footer">
		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @pin.image.url(:medium) %>
			</div>

			<div class="panel-body">
				<p><%= @pin.description %></p>
				<p><strong><%= @pin.user.name if @pin.user %></strong></p>
				<% if @pin.user == current_user %>
					<%= link_to edit_pin_path(@pin) do %>
              			<span class="glyphicon glyphicon-edit"></span> Edit
            		<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>